name: patchhive
services:
  - name: patchhive-db
    type: postgres
    plan: starter

  - name: patchhive-api
    type: web
    github:
      repo: scrimshawlife-ctrl/Patch-Hive
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${APP_SECRET_KEY}
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
      - key: PORT
        scope: RUN_TIME
        value: "8000"
    health_check:
      http_path: /health
      port: 8000
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: patchhive-web
    type: static
    github:
      repo: scrimshawlife-ctrl/Patch-Hive
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${API_URL}
    routes:
      - path: /
    catchall_document: index.html
